{% set version = "1.4.1" %}

package:
  name: openalea.lignum
  version: {{ version }}

source:
  #git_url: https://github.com/pradal/lignum
  path: ..
  script: python setup.py install

build:
  number: 0
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools
    - openalea.mtg
    - vplants.plantgl

test:
  imports:
    - lignum

about:
  home: http://github.com/pradal/lignum
  license: Cecill-C
  summary: OpenAlea.Lignum is a bridge between the LIGNUM FSPM simulation platform and OpenAlea.
