package:
  name: openalea.lignum
  version: 1.4.0

source:
  git_url: https://github.com/pradal/lignum


build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools
    - openalea.mtg
    - vplants.plantgl
    - numpy x.x

test:
  imports:
    - lignum

about:
  home: http://github.com/pradal/lignum
  license: Cecill-C License